/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.ClaseFactura;
import Clases.ConexionDB;
import Clases.Rut;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Jhoan
 */
public class Factura extends javax.swing.JFrame {

    private static ClaseFactura Fact = new ClaseFactura();
    Rut rut = new Rut();
    ConexionDB db = new ConexionDB();
    int y, x;

    public Factura(ClaseFactura factura) {
        initComponents();
        this.IniciarComponentes();
        this.numerofactura.setText(factura.getNfactura());
        this.Fecha.setText(factura.getFecha());
        this.numerocuenta.setText("N.Cuenta:" + factura.getNcuenta());
        this.Ciudad.setText(factura.getCiudad());
        this.Tipo.setText("Tipo:"+factura.getTipo());
        this.Valor.setText("Valor:"+factura.getValor());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Ciudad = new javax.swing.JLabel();
        numerofactura = new javax.swing.JLabel();
        numerocuenta = new javax.swing.JLabel();
        MoverBtn = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Salir = new javax.swing.JLabel();
        Salir2 = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        Valor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("BancoX");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        Fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Fecha.setText("Fecha");
        jPanel1.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 220, -1));

        Ciudad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ciudad.setText("Ciudad");
        jPanel1.add(Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 220, -1));

        numerofactura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numerofactura.setText("Factura");
        jPanel1.add(numerofactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 180, -1));

        numerocuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numerocuenta.setText("Cuenta");
        jPanel1.add(numerocuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 220, -1));

        MoverBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Mover.png"))); // NOI18N
        MoverBtn.setText("jLabel3");
        MoverBtn.setPreferredSize(new java.awt.Dimension(20, 20));
        MoverBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoverBtnMouseDragged(evt);
            }
        });
        MoverBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoverBtnMousePressed(evt);
            }
        });
        jPanel1.add(MoverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Minimize.png"))); // NOI18N
        Minimizar.setText("jLabel2");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 20, 20));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png"))); // NOI18N
        Salir.setText("jLabel2");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 20, 40));

        Salir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png"))); // NOI18N
        Salir2.setText("jLabel2");
        Salir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Salir2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Salir2MouseExited(evt);
            }
        });
        jPanel1.add(Salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 20, 20));

        Tipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tipo.setText("Tipo");
        jPanel1.add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 210, -1));

        Valor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Valor.setText("Valor");
        jPanel1.add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 338, 298));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MoverBtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverBtnMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MoverBtnMouseDragged

    private void MoverBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverBtnMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MoverBtnMousePressed

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        
    }//GEN-LAST:event_SalirMouseExited

    private void Salir2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir2MouseExited
        
    }//GEN-LAST:event_Salir2MouseExited

    private void Salir2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir2MouseEntered
      
    }//GEN-LAST:event_Salir2MouseEntered

    private void Salir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir2MouseClicked
        this.dispose();
    }//GEN-LAST:event_Salir2MouseClicked
    private void IniciarComponentes() {
        this.setLocationRelativeTo(null);
        
        db.conexion();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura(Fact).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ciudad;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel MoverBtn;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel Salir2;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel Valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numerocuenta;
    private javax.swing.JLabel numerofactura;
    // End of variables declaration//GEN-END:variables
}
