/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.ConexionDB;
import Clases.MetodosDeDB;
import Clases.Rut;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;


import javax.swing.JFileChooser;

/**
 *
 * @author Jhoan
 */
public class Login extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Atm
     */
    ConexionDB db = new ConexionDB();
    Rut rut = new Rut();
    MetodosDeDB MetodosDB = new MetodosDeDB();
    public static int Doc;
    public static String Correo;

    public Login() {
        initComponents();
        this.InitComponentes();
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        Bicicleta = new javax.swing.JLabel();
        Salir = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        Olvide = new javax.swing.JLabel();
        LabContraseña = new javax.swing.JLabel();
        Entrar = new javax.swing.JButton();
        txtContra = new javax.swing.JPasswordField();
        MostrarContraseña = new javax.swing.JLabel();
        MoverBtn = new javax.swing.JLabel();
        LabUsuario = new javax.swing.JLabel();
        Registrarme = new javax.swing.JLabel();
        AvisoContraIncorrecta = new javax.swing.JLabel();
        Expandir = new javax.swing.JLabel();
        MenuExpansivo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login1");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        Login.setPreferredSize(new java.awt.Dimension(550, 350));
        Login.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LoginMouseDragged(evt);
            }
        });
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginMousePressed(evt);
            }
        });
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bicicleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Bicicleta.png"))); // NOI18N
        Bicicleta.setText("Bicileta");
        Login.add(Bicicleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 130));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png"))); // NOI18N
        Salir.setText("jLabel2");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        Login.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 20, 20));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Minimize.png"))); // NOI18N
        Minimizar.setText("jLabel2");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        Login.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 20, 20));

        txtUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, -1));

        Olvide.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Olvide.setText("Olvidé mi contraseña");
        Olvide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Olvide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OlvideMouseClicked(evt);
            }
        });
        Login.add(Olvide, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        LabContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabContraseña.setText("Contraseña");
        Login.add(LabContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        Entrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Entrar.setText("Entrar");
        Entrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(13, 51, 51), 1, true));
        Entrar.setContentAreaFilled(false);
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                EntrarHierarchyChanged(evt);
            }
        });
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        Login.add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 80, 30));

        txtContra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 160, -1));

        MostrarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Ojo.png"))); // NOI18N
        MostrarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MostrarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarContraseñaMouseClicked(evt);
            }
        });
        Login.add(MostrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 20, 20));

        MoverBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Mover.png"))); // NOI18N
        MoverBtn.setText("jLabel3");
        MoverBtn.setPreferredSize(new java.awt.Dimension(20, 20));
        MoverBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoverBtnMouseDragged(evt);
            }
        });
        MoverBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoverBtnMousePressed(evt);
            }
        });
        Login.add(MoverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        LabUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabUsuario.setText("Correo");
        Login.add(LabUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        Registrarme.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Registrarme.setText("Registrarme");
        Registrarme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registrarme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarmeMouseClicked(evt);
            }
        });
        Login.add(Registrarme, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        AvisoContraIncorrecta.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        AvisoContraIncorrecta.setForeground(new java.awt.Color(255, 51, 51));
        AvisoContraIncorrecta.setText("Contraseña incorrecta");
        Login.add(AvisoContraIncorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        Expandir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Abajo.png"))); // NOI18N
        Expandir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpandirMouseClicked(evt);
            }
        });
        Login.add(Expandir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 20, 20));

        MenuExpansivo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MenuExpansivoLayout = new javax.swing.GroupLayout(MenuExpansivo);
        MenuExpansivo.setLayout(MenuExpansivoLayout);
        MenuExpansivoLayout.setHorizontalGroup(
            MenuExpansivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        MenuExpansivoLayout.setVerticalGroup(
            MenuExpansivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Login.add(MenuExpansivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 110, 50));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 416, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int x, y;
    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit.png")));
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png")));
    }//GEN-LAST:event_SalirMouseExited

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void MostrarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarContraseñaMouseClicked
        if ("*".equals(String.valueOf(txtContra.getEchoChar()))) {
            txtContra.setEchoChar((char) 0);
        } else {
            txtContra.setEchoChar('*');
        }
    }//GEN-LAST:event_MostrarContraseñaMouseClicked

    private void EntrarHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_EntrarHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_EntrarHierarchyChanged

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
       this.db.conexion();

        String ConsultaContra = "", ConsultaDocumento = "", Usuario, Contra;

        Usuario = txtUsuario.getText();

        Contra = String.valueOf(this.txtContra.getPassword());

        try {
            ConsultaContra = this.MetodosDB.consultarpor(5, 2, Usuario);
            ConsultaDocumento = this.MetodosDB.consultarpor(3, 2, Usuario);

            if (ConsultaContra.equals(Contra)) {
                System.out.println("Contraseña Correcta");
                this.Doc = Integer.parseInt(ConsultaDocumento);
                this.Correo = txtUsuario.getText();
                System.out.println(this.Doc + "" + this.Correo);
                Menuopciones1 Menuopciones1 = new Menuopciones1();
                this.dispose();
                Menuopciones1.setVisible(true);

            } else {
                System.out.println("Contraseña incorrecta/ no ingresó contraseña");
                this.AvisoContraIncorrecta.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println("Error no se encontró" + e);

        }


    }//GEN-LAST:event_EntrarActionPerformed

    private void MoverBtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverBtnMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);

    }//GEN-LAST:event_MoverBtnMouseDragged

    private void MoverBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverBtnMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MoverBtnMousePressed

    private void LoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_LoginMousePressed

    private void LoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);

    }//GEN-LAST:event_LoginMouseDragged

    private void RegistrarmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarmeMouseClicked
        Registro Registro1 = new Registro();
        this.dispose();
        Registro1.setVisible(true);
    }//GEN-LAST:event_RegistrarmeMouseClicked

    private void OlvideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OlvideMouseClicked
        OlvideContra Olvide = new OlvideContra();

        this.dispose();
        Olvide.setVisible(true);
    }//GEN-LAST:event_OlvideMouseClicked

    private void ExpandirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpandirMouseClicked
        if (this.MenuExpansivo.isVisible() == true) {
            this.MenuExpansivo.setVisible(false);
        } else {
            this.MenuExpansivo.setVisible(true);
        }
    }//GEN-LAST:event_ExpandirMouseClicked

    public static int getDoc() {
        return Doc;
    }

    
    
    public void InitComponentes() {
        db.conexion();
        this.setTitle("ATM JhoanV");
        this.setLocationRelativeTo(null);
        this.AvisoContraIncorrecta.setVisible(false);
        this.MenuExpansivo.setVisible(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/IconoBarraTareas.png")));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvisoContraIncorrecta;
    private javax.swing.JLabel Bicicleta;
    private javax.swing.JButton Entrar;
    private javax.swing.JLabel Expandir;
    private javax.swing.JLabel LabContraseña;
    private javax.swing.JLabel LabUsuario;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel MenuExpansivo;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel MostrarContraseña;
    private javax.swing.JLabel MoverBtn;
    private javax.swing.JLabel Olvide;
    private javax.swing.JLabel Registrarme;
    private javax.swing.JLabel Salir;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
