/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.ConexionDB;
import Clases.Rut;
import java.awt.Toolkit;
import java.sql.ResultSet;

/**
 *
 * @author Jhoan
 */
public class OlvideContra extends javax.swing.JFrame {

    ConexionDB db = new ConexionDB();
    Rut rut = new Rut();

    /**
     * Creates new form OlvideContra
     */
    public OlvideContra() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ContraIgual.setVisible(false);
        this.DatosIncorrectos.setVisible(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/IconoBarraTareas.png")));
        
        db.conexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bicicleta = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        MostrarContraseña = new javax.swing.JLabel();
        BtnCambiarContra = new javax.swing.JButton();
        LabDocumento = new javax.swing.JLabel();
        Contraseña2 = new javax.swing.JPasswordField();
        LabConfirmarContraseña = new javax.swing.JLabel();
        LabContraseña = new javax.swing.JLabel();
        LabCorreo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        LabUsuario = new javax.swing.JLabel();
        MostrarContraseña1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        Contraseña = new javax.swing.JPasswordField();
        DatosIncorrectos = new javax.swing.JLabel();
        ContraIgual = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Salir = new javax.swing.JLabel();
        Salir1 = new javax.swing.JLabel();
        Atras = new javax.swing.JLabel();
        MoverBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(416, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bicicleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Bicicleta.png"))); // NOI18N
        Bicicleta.setText("Bicileta");
        jPanel1.add(Bicicleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        txtDocumento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 160, -1));

        MostrarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Ojo.png"))); // NOI18N
        MostrarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarContraseñaMouseClicked(evt);
            }
        });
        jPanel1.add(MostrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 284, -1, -1));

        BtnCambiarContra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCambiarContra.setText("Cambiar Contraseña");
        BtnCambiarContra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(13, 51, 51), 1, true));
        BtnCambiarContra.setContentAreaFilled(false);
        BtnCambiarContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCambiarContra.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                BtnCambiarContraHierarchyChanged(evt);
            }
        });
        BtnCambiarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambiarContraActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCambiarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 120, 30));

        LabDocumento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabDocumento.setText("Documento");
        jPanel1.add(LabDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        Contraseña2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 344, 160, -1));

        LabConfirmarContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabConfirmarContraseña.setText("Confirmar Contraseña");
        jPanel1.add(LabConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 322, -1, -1));

        LabContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabContraseña.setText("Nueva Contraseña");
        jPanel1.add(LabContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 260, -1, -1));

        LabCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabCorreo.setText("Correo");
        jPanel1.add(LabCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        txtUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, -1));

        LabUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabUsuario.setText("Usuario");
        jPanel1.add(LabUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        MostrarContraseña1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Ojo.png"))); // NOI18N
        MostrarContraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarContraseña1MouseClicked(evt);
            }
        });
        jPanel1.add(MostrarContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 346, -1, -1));

        txtCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 160, -1));

        Contraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 284, 160, -1));

        DatosIncorrectos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        DatosIncorrectos.setText("Datos incorrectos, intente otra vez.");
        jPanel1.add(DatosIncorrectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        ContraIgual.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ContraIgual.setText("La contraseña no es igual, intente otra vez.");
        jPanel1.add(ContraIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Minimize.png"))); // NOI18N
        Minimizar.setText("jLabel2");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 0, 20, -1));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png"))); // NOI18N
        Salir.setText("jLabel2");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 0, 20, -1));

        Salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png"))); // NOI18N
        Salir1.setText("jLabel2");
        Salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Salir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Salir1MouseExited(evt);
            }
        });
        jPanel1.add(Salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 0, 20, -1));

        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png"))); // NOI18N
        Atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AtrasMouseExited(evt);
            }
        });
        jPanel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        MoverBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Mover.png"))); // NOI18N
        MoverBtn.setText("jLabel3");
        MoverBtn.setPreferredSize(new java.awt.Dimension(20, 20));
        MoverBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoverBtnMouseDragged(evt);
            }
        });
        MoverBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoverBtnMousePressed(evt);
            }
        });
        jPanel1.add(MoverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarContraseñaMouseClicked
        if ("*".equals(String.valueOf(Contraseña.getEchoChar()))) {
            Contraseña.setEchoChar((char) 0);
        } else {
            Contraseña.setEchoChar('*');
        }
    }//GEN-LAST:event_MostrarContraseñaMouseClicked

    private void BtnCambiarContraHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_BtnCambiarContraHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCambiarContraHierarchyChanged

    private void BtnCambiarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambiarContraActionPerformed

        String Consulta, Editar, Usuario, Correo, Documento, Contra, ConfirmarContra;

        Usuario = this.txtUsuario.getText();
        Correo = this.txtCorreo.getText();
        Documento = this.txtDocumento.getText();
        Contra = String.valueOf(this.Contraseña.getPassword());
        ConfirmarContra = String.valueOf(this.Contraseña2.getPassword());

        Consulta = "SELECT pers_Contrasena,pers_Usuario,pers_Documento FROM Persona where pers_Correo ='" + Correo + "';";
        Editar = ("UPDATE Persona set pers_Contrasena = '" + Contra + "' where pers_Correo = '" + Correo + "';");
        try {
            if (Contra.equals(ConfirmarContra)) {

                ResultSet RESPUESTA = db.consultar(Consulta);
                if (RESPUESTA.getString("pers_Usuario").equals(Usuario)
                        && RESPUESTA.getString("pers_Documento").equals(Documento)) {

                    db.Editar(Editar);

                    Login Login1 = new Login();
                    Login1.setVisible(true);
                    this.dispose();
                    System.out.println("Cambio de contraseña correcto");

                } else {
                    System.out.println("Contraseña incorrecta/ no ingresó contraseña");
                    this.DatosIncorrectos.setVisible(true);
                }
            } else {
                System.out.println("La contraseña no es igual");
                this.ContraIgual.setVisible(true);
            }
        } catch (Exception e) {
            this.DatosIncorrectos.setVisible(true);
            System.out.println("Error, datos incorrectos" + e);
        }

    }//GEN-LAST:event_BtnCambiarContraActionPerformed

    private void MostrarContraseña1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarContraseña1MouseClicked
        if ("*".equals(String.valueOf(Contraseña2.getEchoChar()))) {
            Contraseña2.setEchoChar((char) 0);
        } else {
            Contraseña2.setEchoChar('*');
        }
    }//GEN-LAST:event_MostrarContraseña1MouseClicked
    int x, y;
    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit.png")));
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png")));
    }//GEN-LAST:event_SalirMouseExited

    private void Salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Salir1MouseClicked

    private void Salir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Salir1MouseEntered

    private void Salir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Salir1MouseExited

    private void AtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasMouseClicked
        Login Login1 = new Login();
        Login1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasMouseClicked

    private void MoverBtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverBtnMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MoverBtnMouseDragged

    private void MoverBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverBtnMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MoverBtnMousePressed

    private void AtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasMouseEntered
        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras azul.png")));
    }//GEN-LAST:event_AtrasMouseEntered

    private void AtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasMouseExited
        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png")));
    }//GEN-LAST:event_AtrasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OlvideContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OlvideContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OlvideContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OlvideContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OlvideContra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atras;
    private javax.swing.JLabel Bicicleta;
    private javax.swing.JButton BtnCambiarContra;
    private javax.swing.JLabel ContraIgual;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JPasswordField Contraseña2;
    private javax.swing.JLabel DatosIncorrectos;
    private javax.swing.JLabel LabConfirmarContraseña;
    private javax.swing.JLabel LabContraseña;
    private javax.swing.JLabel LabCorreo;
    private javax.swing.JLabel LabDocumento;
    private javax.swing.JLabel LabUsuario;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel MostrarContraseña;
    private javax.swing.JLabel MostrarContraseña1;
    private javax.swing.JLabel MoverBtn;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel Salir1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
