/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.ConexionDB;
import Clases.Personas;
import Clases.Rut;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jhoan
 */
public class Registro extends javax.swing.JFrame {

    ConexionDB db = new ConexionDB();
    Rut rut = new Rut();
    Personas Person = new Personas();

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.DatosIncorrectos.setVisible(false);
        this.ContraIgual.setVisible(false);
        this.DocYaExistente.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setTitle("ATM JhoanV");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/IconoBarraTareas.png")));
        try {
            
            db.conexion();

        } catch (Exception e) {
            System.out.println("Error no se encontró la base de datos en el try catch del init" + e);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bicicleta = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        MostrarContraseña = new javax.swing.JLabel();
        BtnRegistrarse = new javax.swing.JButton();
        LabDocumento = new javax.swing.JLabel();
        LabDireccion = new javax.swing.JLabel();
        Contraseña2 = new javax.swing.JPasswordField();
        LabConfirmarContraseña = new javax.swing.JLabel();
        LabContraseña = new javax.swing.JLabel();
        LabCorreo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        LabUsuario = new javax.swing.JLabel();
        MostrarContraseña1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        Contraseña = new javax.swing.JPasswordField();
        DatosIncorrectos = new javax.swing.JLabel();
        ContraIgual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Salir = new javax.swing.JLabel();
        Atras = new javax.swing.JLabel();
        DocYaExistente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(416, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bicicleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Bicicleta.png"))); // NOI18N
        Bicicleta.setText("Bicileta");
        jPanel1.add(Bicicleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        txtDocumento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 166, 160, -1));

        MostrarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Ojo.png"))); // NOI18N
        MostrarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarContraseñaMouseClicked(evt);
            }
        });
        jPanel1.add(MostrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 284, -1, -1));

        BtnRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnRegistrarse.setText("Registrarse");
        BtnRegistrarse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(13, 51, 51), 1, true));
        BtnRegistrarse.setContentAreaFilled(false);
        BtnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegistrarse.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                BtnRegistrarseHierarchyChanged(evt);
            }
        });
        BtnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 80, 30));

        LabDocumento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabDocumento.setText("Documento");
        jPanel1.add(LabDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 146, -1, -1));

        LabDireccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabDireccion.setText("Direccion");
        jPanel1.add(LabDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 206, -1, -1));

        Contraseña2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 344, 160, -1));

        LabConfirmarContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabConfirmarContraseña.setText("Confirmar Contraseña");
        jPanel1.add(LabConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 322, -1, -1));

        LabContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabContraseña.setText("Contraseña");
        jPanel1.add(LabContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 260, -1, -1));

        LabCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabCorreo.setText("Correo");
        jPanel1.add(LabCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 86, -1, -1));

        txtUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 46, 160, -1));

        LabUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabUsuario.setText("Usuario");
        jPanel1.add(LabUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 26, -1, -1));

        MostrarContraseña1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Ojo.png"))); // NOI18N
        MostrarContraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarContraseña1MouseClicked(evt);
            }
        });
        jPanel1.add(MostrarContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 346, -1, -1));

        txtCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 114, 160, -1));

        txtDireccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 228, 160, -1));

        Contraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 284, 160, -1));

        DatosIncorrectos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        DatosIncorrectos.setText("Datos incorrectos, intente otra vez.");
        jPanel1.add(DatosIncorrectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        ContraIgual.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ContraIgual.setText("La contraseña no es igual, intente otra vez.");
        jPanel1.add(ContraIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Mover.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(20, 20));
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 0, -1, -1));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Minimize.png"))); // NOI18N
        Minimizar.setText("jLabel2");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 0, 20, -1));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png"))); // NOI18N
        Salir.setText("jLabel2");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 0, 20, -1));

        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png"))); // NOI18N
        Atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AtrasMouseExited(evt);
            }
        });
        jPanel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        DocYaExistente.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        DocYaExistente.setText("El Documento ya existe, Escriba otro");
        jPanel1.add(DocYaExistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarContraseñaMouseClicked
        if ("*".equals(String.valueOf(Contraseña.getEchoChar()))) {
            Contraseña.setEchoChar((char) 0);
        } else {
            Contraseña.setEchoChar('*');
        }
    }//GEN-LAST:event_MostrarContraseñaMouseClicked

    private void BtnRegistrarseHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_BtnRegistrarseHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistrarseHierarchyChanged

    private void BtnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarseActionPerformed

        String Persona, Usuario, Correo, Documento, Direccion, Contra, ConfirmarContra, ConsultaDocumento;
        int Dinero;
        Usuario = this.txtUsuario.getText();
        Correo = this.txtCorreo.getText();
        Documento = this.txtDocumento.getText();
        Direccion = this.txtDireccion.getText();
        Contra = String.valueOf(this.Contraseña.getPassword());
        ConfirmarContra = String.valueOf(this.Contraseña2.getPassword());
        Dinero = (int) (Math.random() * 1000000 * Math.random());
        System.out.println(Dinero);
        boolean Existe = false;
        Persona = "INSERT INTO Persona (pers_id,pers_Usuario,pers_Correo,pers_Documento,pers_Direccion,pers_Contrasena,pers_dinero) "
                + "values (null," + "'" + Usuario + "'" + "," + "'" + Correo + "'" + "," + "'" + Documento
                + "'" + "," + "'" + Direccion + "'" + "," + "'" + Contra + "'" + "," + "'" + Dinero + "'" + ")";
        try {
            if (Contra.isEmpty() == false) {

                if (Contra.equals(ConfirmarContra)) {

                    try {
                        ConsultaDocumento = ("select pers_Documento from Persona;");
                        ResultSet DOCUMENTO = db.consultar(ConsultaDocumento);
                        while (DOCUMENTO.next()) {

                            if (DOCUMENTO.getString("pers_Documento").equals(Documento)) {
                                System.out.println("El documento ya existe"
                                        + "");
                                Existe = true;
                                break;
                            }

                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
                        Existe = false;
                    }

                    if (Existe == true) {
                        this.DocYaExistente.setVisible(true);
                    }
                    if (Existe == false) {
                        db.insertar(Persona);
                        System.out.println("Registro completo");
                        Login Login1 = new Login();
                        Login1.setVisible(true);
                        this.dispose();
                    }

                } else {
                    this.ContraIgual.setVisible(true);
                }
            } else {
                this.DatosIncorrectos.setVisible(true);
            }

        } catch (Exception e) {
            this.DatosIncorrectos.setVisible(true);
            System.out.println("Error, datos incorrectos" + e);
        }


    }//GEN-LAST:event_BtnRegistrarseActionPerformed

    private void MostrarContraseña1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarContraseña1MouseClicked
        if ("*".equals(String.valueOf(Contraseña2.getEchoChar()))) {
            Contraseña2.setEchoChar((char) 0);
        } else {
            Contraseña2.setEchoChar('*');
        }
    }//GEN-LAST:event_MostrarContraseña1MouseClicked

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);

    }//GEN-LAST:event_jLabel3MouseDragged
    int x, y;
    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel3MousePressed

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit.png")));
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png")));
    }//GEN-LAST:event_SalirMouseExited

    private void AtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasMouseClicked
        Login Login1 = new Login();
        Login1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasMouseClicked

    private void AtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasMouseEntered
        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras azul.png")));
    }//GEN-LAST:event_AtrasMouseEntered

    private void AtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasMouseExited
        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png")));
    }//GEN-LAST:event_AtrasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atras;
    private javax.swing.JLabel Bicicleta;
    private javax.swing.JButton BtnRegistrarse;
    private javax.swing.JLabel ContraIgual;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JPasswordField Contraseña2;
    private javax.swing.JLabel DatosIncorrectos;
    private javax.swing.JLabel DocYaExistente;
    private javax.swing.JLabel LabConfirmarContraseña;
    private javax.swing.JLabel LabContraseña;
    private javax.swing.JLabel LabCorreo;
    private javax.swing.JLabel LabDireccion;
    private javax.swing.JLabel LabDocumento;
    private javax.swing.JLabel LabUsuario;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel MostrarContraseña;
    private javax.swing.JLabel MostrarContraseña1;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
