/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import Clases.ConexionDB;
import Clases.MetodosDeDB;

import Clases.Rut;
import java.awt.Color;
import java.awt.Toolkit;
/**
 *
 * @author Jhoan
 */
public class retiroahorro extends javax.swing.JFrame {
    int x,y;
    ConexionDB db = new ConexionDB();
    Rut rut = new Rut();
    Login log = new Login();
    double ValorAConsignar;
    MetodosDeDB MetodosDB = new MetodosDeDB();
    /**
     * Creates new form retiroahorro
     */
    public retiroahorro() {
        initComponents();
        
        db.conexion();
        this.setTitle("ATM JhoanV");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/IconoBarraTareas.png")));
        this.setLocationRelativeTo(null);
        this.Menuborde.setVisible(false);
        this.txtDinero.setText(this.MetodosDB.ConsultarDineroPorDocumento(this.log.Doc));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        MenuUSER = new javax.swing.JPanel();
        MenuUsuario = new javax.swing.JLabel();
        Atras4 = new javax.swing.JLabel();
        Menuborde = new javax.swing.JPanel();
        CerrarSesion = new javax.swing.JLabel();
        Perfil = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        MoverBtn = new javax.swing.JLabel();
        Salir = new javax.swing.JLabel();
        Consignar = new javax.swing.JCheckBox();
        Retirar = new javax.swing.JCheckBox();
        ClavePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        BtnSiguienteClave = new javax.swing.JButton();
        DineroPanel = new javax.swing.JPanel();
        txtDinero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        RetirarPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtRetirar = new javax.swing.JTextField();
        BtnSiguienteRetirar = new javax.swing.JButton();
        ConsignarPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtConsignar = new javax.swing.JTextField();
        BtnSiguienteConsignar1 = new javax.swing.JButton();
        ConsignarCuenta = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCuentaConsignar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelPrincipal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelPrincipalMouseDragged(evt);
            }
        });
        PanelPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelPrincipalMousePressed(evt);
            }
        });
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuUSER.setBackground(new java.awt.Color(255, 255, 255));
        MenuUSER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/usuario (1).png"))); // NOI18N
        MenuUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuUsuarioMouseClicked(evt);
            }
        });
        MenuUSER.add(MenuUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 0, -1, -1));

        Atras4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png"))); // NOI18N
        Atras4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Atras4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Atras4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Atras4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Atras4MouseExited(evt);
            }
        });
        MenuUSER.add(Atras4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        PanelPrincipal.add(MenuUSER, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        Menuborde.setBackground(new java.awt.Color(255, 255, 255));
        Menuborde.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Menuborde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CerrarSesion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseExited(evt);
            }
        });
        Menuborde.add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 20));

        Perfil.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Perfil.setText("Perfil");
        Perfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PerfilMouseEntered(evt);
            }
        });
        Menuborde.add(Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        PanelPrincipal.add(Menuborde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/icono2.png"))); // NOI18N
        PanelPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 180, 190));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Minimize.png"))); // NOI18N
        Minimizar.setText("jLabel2");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        PanelPrincipal.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 20, 20));

        MoverBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Mover.png"))); // NOI18N
        MoverBtn.setText("jLabel3");
        MoverBtn.setPreferredSize(new java.awt.Dimension(20, 20));
        MoverBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoverBtnMouseDragged(evt);
            }
        });
        MoverBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoverBtnMousePressed(evt);
            }
        });
        PanelPrincipal.add(MoverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png"))); // NOI18N
        Salir.setText("jLabel2");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        PanelPrincipal.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 20, 20));

        Consignar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Consignar.setText("Consignar");
        Consignar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Consignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsignarMouseClicked(evt);
            }
        });
        Consignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsignarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(Consignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        Retirar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Retirar.setText("Retirar");
        Retirar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(Retirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 80, -1));

        ClavePanel.setBackground(new java.awt.Color(255, 255, 255));
        ClavePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Por favor introduzca su clave");

        txtClave.setEditable(false);

        BtnSiguienteClave.setText("Enviar");
        BtnSiguienteClave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSiguienteClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteClaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClavePanelLayout = new javax.swing.GroupLayout(ClavePanel);
        ClavePanel.setLayout(ClavePanelLayout);
        ClavePanelLayout.setHorizontalGroup(
            ClavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClavePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ClavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClavePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClavePanelLayout.createSequentialGroup()
                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClavePanelLayout.createSequentialGroup()
                        .addComponent(BtnSiguienteClave)
                        .addGap(47, 47, 47))))
        );
        ClavePanelLayout.setVerticalGroup(
            ClavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClavePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(BtnSiguienteClave)
                .addContainerGap())
        );

        PanelPrincipal.add(ClavePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        DineroPanel.setBackground(new java.awt.Color(255, 255, 255));
        DineroPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        DineroPanel.setPreferredSize(new java.awt.Dimension(176, 100));

        txtDinero.setEditable(false);
        txtDinero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Usted tiene en su cuenta");

        javax.swing.GroupLayout DineroPanelLayout = new javax.swing.GroupLayout(DineroPanel);
        DineroPanel.setLayout(DineroPanelLayout);
        DineroPanelLayout.setHorizontalGroup(
            DineroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DineroPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(DineroPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DineroPanelLayout.setVerticalGroup(
            DineroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DineroPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        PanelPrincipal.add(DineroPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, -1));

        RetirarPanel.setBackground(new java.awt.Color(255, 255, 255));
        RetirarPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        RetirarPanel.setPreferredSize(new java.awt.Dimension(176, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Valor a retirar");

        BtnSiguienteRetirar.setText("Siguiente");

        javax.swing.GroupLayout RetirarPanelLayout = new javax.swing.GroupLayout(RetirarPanel);
        RetirarPanel.setLayout(RetirarPanelLayout);
        RetirarPanelLayout.setHorizontalGroup(
            RetirarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetirarPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(RetirarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RetirarPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BtnSiguienteRetirar)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        RetirarPanelLayout.setVerticalGroup(
            RetirarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetirarPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnSiguienteRetirar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        PanelPrincipal.add(RetirarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 170, 120));

        ConsignarPanel.setBackground(new java.awt.Color(255, 255, 255));
        ConsignarPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ConsignarPanel.setPreferredSize(new java.awt.Dimension(176, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Valor a consignar");

        BtnSiguienteConsignar1.setText("Siguiente");
        BtnSiguienteConsignar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteConsignar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsignarPanelLayout = new javax.swing.GroupLayout(ConsignarPanel);
        ConsignarPanel.setLayout(ConsignarPanelLayout);
        ConsignarPanelLayout.setHorizontalGroup(
            ConsignarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsignarPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(ConsignarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtConsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ConsignarPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BtnSiguienteConsignar1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        ConsignarPanelLayout.setVerticalGroup(
            ConsignarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsignarPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtConsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnSiguienteConsignar1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        PanelPrincipal.add(ConsignarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 170, 120));

        ConsignarCuenta.setBackground(new java.awt.Color(255, 255, 255));
        ConsignarCuenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ConsignarCuenta.setPreferredSize(new java.awt.Dimension(176, 100));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Cuenta a consignar");

        javax.swing.GroupLayout ConsignarCuentaLayout = new javax.swing.GroupLayout(ConsignarCuenta);
        ConsignarCuenta.setLayout(ConsignarCuentaLayout);
        ConsignarCuentaLayout.setHorizontalGroup(
            ConsignarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsignarCuentaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(ConsignarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtCuentaConsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        ConsignarCuentaLayout.setVerticalGroup(
            ConsignarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsignarCuentaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCuentaConsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        PanelPrincipal.add(ConsignarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 170, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUsuarioMouseClicked
        if (this.Menuborde.isVisible() == true) {
            this.Menuborde.setVisible(false);
        } else {
            this.Menuborde.setVisible(true);
        }
    }//GEN-LAST:event_MenuUsuarioMouseClicked

    private void Atras4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Atras4MouseClicked
        Menuopciones1 Menu1 = new Menuopciones1();
        Menu1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Atras4MouseClicked

    private void Atras4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Atras4MouseEntered
        Atras4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras azul.png")));
    }//GEN-LAST:event_Atras4MouseEntered

    private void Atras4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Atras4MouseExited
        Atras4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png")));
    }//GEN-LAST:event_Atras4MouseExited

    private void CerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseExited
        this.CerrarSesion.setBackground(Color.WHITE);
    }//GEN-LAST:event_CerrarSesionMouseExited

    private void PerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerfilMouseEntered
        this.CerrarSesion.setBackground(Color.getHSBColor(72, 28, 100));
    }//GEN-LAST:event_PerfilMouseEntered

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void MoverBtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverBtnMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MoverBtnMouseDragged

    private void MoverBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverBtnMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MoverBtnMousePressed

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit.png")));
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png")));
    }//GEN-LAST:event_SalirMouseExited

    private void ConsignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsignarMouseClicked
        if (this.Consignar.isSelected() == true) {
            this.Retirar.setSelected(false);
            this.ConsignarPanel.setVisible(true);
        }
        this.ConsignarPanel.setVisible(true);
    }//GEN-LAST:event_ConsignarMouseClicked

    private void ConsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsignarActionPerformed

    private void RetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarActionPerformed
        if (this.Retirar.isSelected() == true) {
            this.Consignar.setSelected(false);
        }
    }//GEN-LAST:event_RetirarActionPerformed

    private void BtnSiguienteClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSiguienteClaveActionPerformed

    private void BtnSiguienteConsignar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteConsignar1ActionPerformed
        this.ValorAConsignar = Double.parseDouble(this.txtConsignar.getText());
        this.ConsignarPanel.setVisible(false);
        this.ConsignarCuenta.setVisible(true);
    }//GEN-LAST:event_BtnSiguienteConsignar1ActionPerformed

    private void PanelPrincipalMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPrincipalMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_PanelPrincipalMouseDragged

    private void PanelPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPrincipalMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_PanelPrincipalMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(retiroahorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(retiroahorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(retiroahorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(retiroahorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new retiroahorro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atras4;
    private javax.swing.JButton BtnSiguienteClave;
    private javax.swing.JButton BtnSiguienteConsignar1;
    private javax.swing.JButton BtnSiguienteRetirar;
    private javax.swing.JLabel CerrarSesion;
    private javax.swing.JPanel ClavePanel;
    private javax.swing.JCheckBox Consignar;
    private javax.swing.JPanel ConsignarCuenta;
    private javax.swing.JPanel ConsignarPanel;
    private javax.swing.JPanel DineroPanel;
    private javax.swing.JPanel MenuUSER;
    private javax.swing.JLabel MenuUsuario;
    private javax.swing.JPanel Menuborde;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel MoverBtn;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel Perfil;
    private javax.swing.JCheckBox Retirar;
    private javax.swing.JPanel RetirarPanel;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtConsignar;
    private javax.swing.JTextField txtCuentaConsignar;
    private javax.swing.JTextField txtDinero;
    private javax.swing.JTextField txtRetirar;
    // End of variables declaration//GEN-END:variables
}
