/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

/**
 *
 * @author Jhoan
 */
public class ClavePanel extends javax.swing.JPanel {

    /**
     * Creates new form ClavePanel
     */
    public ClavePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        BtnSiguienteClave = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Por favor introduzca su clave");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtClave.setEditable(false);
        add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 150, -1));

        BtnSiguienteClave.setText("Enviar");
        BtnSiguienteClave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(BtnSiguienteClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSiguienteClave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtClave;
    // End of variables declaration//GEN-END:variables
}
